"""empty message

Revision ID: 054875ce6643
Revises: 97bdae2d3898
Create Date: 2025-02-03 12:20:17.948284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054875ce6643'
down_revision = '97bdae2d3898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
