"""empty message

Revision ID: 19f838b712cb
Revises: 83363847899f
Create Date: 2025-01-29 16:52:54.772923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f838b712cb'
down_revision = '83363847899f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('extracted_at')
        batch_op.drop_column('extracted_text')

    # ### end Alembic commands ###
