"""empty message

Revision ID: 3e1f5bde0a3f
Revises: 19f838b712cb
Create Date: 2025-01-29 17:03:50.276981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e1f5bde0a3f'
down_revision = '19f838b712cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')
        batch_op.drop_column('extracted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
