"""empty message

Revision ID: 7330c8b5a2a6
Revises: 
Create Date: 2025-02-06 01:00:39.291748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7330c8b5a2a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_files',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], name='user_files_uploaded_file_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_files_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'uploaded_file_id', name='user_files_pkey')
    )
    # ### end Alembic commands ###
