"""empty message

Revision ID: e381fc8840bc
Revises: 3e1f5bde0a3f
Create Date: 2025-01-30 13:12:45.187109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e381fc8840bc'
down_revision = '3e1f5bde0a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_hash', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('extracted_texts_file_id_key', type_='unique')
        batch_op.drop_column('extracted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('extracted_texts_file_id_key', ['file_id'])
        batch_op.drop_column('file_hash')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
